In [9]:
#Zad1
import numpy as np

macierz = np.random.random([10,10])

print("Najmniejszy element:",np.min(macierz))
print("Największy element:",np.max(macierz))
print()

#Zad2  
print(macierz)
print()
for i in range(0, len(macierz), 1):
    print("Największy element w wierszu",i+1,":",max(macierz[i,:]))
print()
    
for i in range(0, len(macierz), 1):
    print("Największy element w kolumnie",i+1,":",max(macierz[:,i]))


Najmniejszy element: 0.006615499700871608
Największy element: 0.9824314641348861

[[0.20707251 0.842401   0.24198084 0.89025539 0.57911388 0.87300519
  0.86502322 0.49910773 0.78950626 0.84147171]
 [0.09234163 0.94512932 0.91269933 0.86869453 0.28953377 0.09446284
  0.66771677 0.87184158 0.70279854 0.60722436]
 [0.37297803 0.85018835 0.27172209 0.42308476 0.85626246 0.15789799
  0.69667338 0.10689124 0.87342814 0.51496203]
 [0.33904318 0.19322114 0.52975394 0.04738976 0.97868081 0.98243146
  0.07321758 0.08340369 0.89677971 0.68114855]
 [0.06913569 0.34681548 0.43177564 0.59526269 0.66667509 0.16122401
  0.88441506 0.77331007 0.68887543 0.97822376]
 [0.7249405  0.89988874 0.50369836 0.17935888 0.17209141 0.26701822
  0.06343857 0.85072776 0.22515489 0.15652781]
 [0.03132573 0.26490828 0.59740055 0.17271267 0.88806998 0.3592452
  0.28871695 0.42210908 0.09297325 0.23230046]
 [0.3000255  0.36285559 0.86399768 0.91238578 0.62811134 0.15448925
  0.57327991 0.09548708 0.77712302 0.10508265]

In [40]:
#Zad3
import numpy as np

macierz = np.zeros([5,5])
print(macierz)
print()

macierz[:,0] = 1
macierz[:,4] = 1
macierz[0,:] = 1
macierz[4,:] = 1
print(macierz)
print()

def zamienWartosci(m):
    for i in range(0, len(m), 1):
        for j in range(0, len(m), 1):
            if m[i][j]== 1:
                m[i][j] = 0
            else:
                m[i][j] =1
    return m

macierz2 = zamienWartosci(macierz)
print(macierz2)





[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [51]:
#Zad4
import numpy as np

macierz1 = np.random.random([5,5])
macierz2 = np.random.random([5,5])
print(macierz1)
print()
print(macierz2)
print()

#a
macierz3 = np.add(macierz1, macierz2)
print(macierz3)
print()

#b
macierz4 = np.subtract(macierz1,macierz2)
print(macierz4)
print()

#c
macierz5 = np.dot(macierz1,macierz2)
print(macierz5)
print()

#d
macierz6 = macierz3 *2 /10
print(macierz6)
print()
#e
macierz7 = macierz6[1:4,1:4]
print(macierz7)
print()

#f
wektor = macierz7.flatten()
print(wektor)


[[0.50674493 0.80978807 0.60845016 0.67841391 0.95231332]
 [0.30441401 0.36969508 0.47840038 0.66301834 0.01661614]
 [0.6888937  0.14049737 0.92218897 0.81321979 0.58482032]
 [0.5099321  0.50111538 0.11320826 0.0982261  0.3226347 ]
 [0.38970282 0.79757144 0.42462037 0.57002325 0.99744812]]

[[0.7121796  0.52345735 0.58858062 0.16341518 0.42620272]
 [0.024247   0.01073506 0.27411763 0.23273272 0.36913088]
 [0.83617684 0.89522299 0.54941851 0.6534272  0.57891457]
 [0.10579325 0.096224   0.41637746 0.87711371 0.7143514 ]
 [0.04940822 0.6748554  0.59665261 0.35269932 0.02292169]]

[[1.21892453 1.33324542 1.19703078 0.84182909 1.37851604]
 [0.328661   0.38043014 0.75251801 0.89575106 0.38574702]
 [1.52507054 1.03572036 1.47160747 1.46664699 1.16373489]
 [0.61572535 0.59733938 0.52958572 0.97533981 1.0369861 ]
 [0.43911104 1.47242684 1.02127298 0.92272257 1.02036981]]

[[-0.20543467  0.28633072  0.01986954  0.51499873  0.5261106 ]
 [ 0.28016701  0.35896003  0.20428275  0.43028562 -0.35251473